### ISSUE TITLE
Traces are kept in RAM which leads to problems for long experiments

### ISSUE THREAD

**Issue by aewag** [Fraunhofer-AISEC/archie#11]
Long running experiments create a lot data. Archie normally writes the data all at once at the end of each experiment. This leads to a memory consumption which can be problematic. I would suggest to incrementally write the data.

**Comment by tibersam** [comment]
With how archie is build i do not see how to do so. I know the memory footprint can be a problem. Incremental write does not work with how all parts operate currently. First all data is stored inside the fault plugin, then send to the worker (raw -> asciihex -> raw), which waits for all data to arrive, then it is processed, then logged by the chosen logger. The biggest memory footprint is reached during processing of the data. 

The current workaround is firstly to by the user to limit the number of parallel running workers, secondly the worker python part is monitored by the scheduler and it decides if it can run another worker. This change probably needs an architectural change of the tool. Or am i overlooking something?

**Comment by aewag** [comment]
Yeah, seems like it needs an architectural change. On our big server I can only run a maximum of 5 to 10 workers in parallel, so most of the time the server CPUs are idle but the RAM is full.

Is there any logical issue with sending out the data as soon as a count limit has been reached within the faultplugin, filter the data in the python scripts and write it?

**Comment by tibersam** [comment]
There is no logical issue rather the current approach was easiest to implement.

But it can lead to artifacts being created in the existing data, that are not meant to  be there through singlestepping. If a TB of lets say 100 instruction is split up with the singlestep behavior into 100 TBs, currently with all data available it is possible to remove them and merge them back into the one TB consisting of 100 instructions. But if the threshold is reached during this a part of the 100 instruction is already written to disk leading to 100 unneeded tb entries. This probably can be solved, but currently i am not sure how. This is the first potential problem i am seeing.

Other question: Is it possible to narrow the scope of your simulation? If for example only one function or one part of a firmware is of interest maybe limit the scope to that part by setting a better start and end? Another solution would be to add more RAM to the server... I know these are workarounds, but they do not require a rewrite of the tool. And i suspect the architecture changes to need at least a good week of development time before they are running smoothly. 

Side note: With the current setup it should be straight forward to add support for clustered environments, but i have never done it and i am missing experience in this filed. With the changes the tool could potentially loose this option.

**Comment by aewag** [comment]
> There is no logical issue rather the current approach was easiest to implement.

Thanks for clarifying! :+1: 
I'll agree that this will probably come with other issues that need to be solved. I think that this change is than a TODO for the future when there is more time.
 
> Other question: Is it possible to narrow the scope of your simulation? If for example only one function or one part of a firmware is of interest maybe limit the scope to that part by setting a better start and end? Another solution would be to add more RAM to the server... I know these are workarounds, but they do not require a rewrite of the tool. And i suspect the architecture changes to need at least a good week of development time before they are running smoothly.

More RAM is unfortunately not an option :D 
But I will see if the experiments can be split or somehow reduced.

**Comment by aewag** [comment]
With #58 this is no longer an issue.
