### ISSUE TITLE
Provide a good description and keywords

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/archie#3]
It would be good to provide a good description and some keywords in the "About" section on GitHub. Let me know, if you have problems accessing it.

**Comment by tibersam** [comment]
Hi,

A good description would be:
ARCHIE is a QEMU-based architecture-independent fault evaluation tool, that is able to simulate transient and permanent instruction and data faults in RAM, flash, and processor registers.

But i do not have the perimissions to change the about section.

**Comment by oxisto** [comment]
Done
