### ISSUE TITLE
Understanding trigger address setting and handling faulted instruction address that occur at the beginning of a TB

### ISSUE THREAD

**Issue by e-shreve-ti** [Fraunhofer-AISEC/archie#32]
I'm seeing some issues with situations where the instruction to be faulted occurs at the start of a TB and a negative trigger_address is specified for the fault. If the instruction to be faulted occurs at the start of a TB then very frequently (perhaps always) ARCHIE either fails to find a trigger instruction or it finds a trigger instruction that executes _after_ the instruction to be faulted. 

It appears to me that search_for_fault_location() searches the wrong direction. goldenrun_tb_exec and goldenrun_tb_info are sorted such that the first index (index 0) is the last TB executed. Thus, to search earlier in the execution, the index value should be increased if the TB at the current index doesn't have the trigger location. However, on lines [62](https://github.com/Fraunhofer-AISEC/archie/blob/3b0bb56/calculate_trigger.py#L62) and [88](https://github.com/Fraunhofer-AISEC/archie/blob/3b0bb56/calculate_trigger.py#L88) the index is decreased.

Also, in case the trigger location is not found, the [while loop](https://github.com/Fraunhofer-AISEC/archie/blob/3b0bb56/calculate_trigger.py#L57) should start with a check that the idx value does not equal or exceed the number of rows in the goldenrun TB data frames. (Or a try block should catch a ValueError when the idx is used in the call to find_tb_info_row.) 

I can open a PR, but wanted to have a discussion first in case I am misunderstanding something.

**Comment by tibersam** [comment]
Did you find these isues in your data? 

If i remember correctly the tables should be reversed before they are given to the calculation function. At least thats how i first implemented it. Could have changed.

You are definitely correct with the while loop. Maybe archie should first check if the fault location is reached during normal execution?

**Comment by e-shreve-ti** [comment]
@tibersam , Yes I can see trigger addresses selected which occur at the end of the _next_ TB when the fault address is at the start of a TB. By "next" I mean next in execution. There are two places where the lists are reversed. If I'm reading the code correctly, the lists passed to search_for_fault_location have been unreversed. The lists are first reversed in [build_filters](https://github.com/Fraunhofer-AISEC/archie/blob/3b0bb56ad3/faultclass.py#L211). Then [calculate_trigger_addresses reverses them](https://github.com/Fraunhofer-AISEC/archie/blob/3b0bb56/calculate_trigger.py#L115) before passing them to search_for_fault_location().

**Comment by tibersam** [comment]
OK. This definitly is a bug, could be the double reversion, that is the problem. Or the strategy is flawed. I will try to investigate this further. If you already have a solution, please open a PR. I don't think you are misunderstanding something. As soon as gitlab is back online (currently has an outage) i also will look further into this

**Comment by tibersam** [comment]
@aewag or @lukasauer can you mark this as a bug?

**Comment by tibersam** [comment]
New theory: If you look into the tbexeclist data you find that it is not sorted correctly. Probably that is why it selects the wrong translation block

**Comment by tibersam** [comment]
@e-shreve-ti can you verify if my [branch](https://github.com/tibersam/archie/tree/fix_trigger_calculation) fixes your problem?

@aewag and @lukasauer did you run into similar problems?

**Comment by aewag** [comment]
> @aewag and @lukasauer did you run into similar problems?

I am not quite sure. I may have missed it, if it occured.

**Comment by e-shreve-ti** [comment]
@tibersam , yes your branch address the issue of finding the correct trigger address for my application. 

However, in case the trigger location is not found, I still think the [while loop](https://github.com/Fraunhofer-AISEC/archie/blob/3b0bb56/calculate_trigger.py#L57) should start with a check that the idx value is in range. Otherwise an uncaught exception terminates the program and none of the experiments are executed. For me, this is now occurring when my fault address range includes the first instruction executed. Or I can file another ticket for this as I do note that the behavior (even if the idx value is checked to avoid an exception) means that the first instruction executed can't be faulted.

**Comment by tibersam** [comment]
OK, we can merge #37.

I am currently looking into the while loop problem. The exception is probably index out of range?
I will change the calculation behaviour to inject the fault at start point, not when the trigger is executed if idx ever gets negativ. Also i will update the calculation to also change the lifespan so that the faulted instruction is not reverted before it is executed.  Am I overlooking something? This will take some time but i try to open the PR this week.

With this the first instruction executed should be fault-able i think.

**Comment by tibersam** [comment]
@aewag can you reopen the issue?

**Comment by e-shreve-ti** [comment]
@tibersam,
The exception in the while loop is a KeyError on this line 
`idtbinfo = find_tb_info_row(goldenrun_tb_exec.at[idx, "tb"], goldenrun_tb_info)`

Yes, supporting faulting the first instruction would be great. Thanks.

**Comment by tibersam** [comment]
@e-shreve-ti can you look into PR #38? I hope this PR fixes your probelm :)

Also could you give me also the line number of the KeyError? the find_tb_info_row is called in two locations inside the function

**Comment by lukasauer** [comment]
It should be [line 58](https://github.com/Fraunhofer-AISEC/archie/blob/master/calculate_trigger.py#L58). I also ran into this error this morning, but did not have the time to look into it yet.

**Comment by e-shreve-ti** [comment]
@tibersam , yes, as @lukasauer said, it is line 58, which is the occurrence at the start of the while loop.

**Comment by lukasauer** [comment]
I just merged pull request #38, which should fix this issue. Thanks for reporting the issue! Feel free to reopen the issue or open a new one, should it not be fixed with the pull request.
