### ISSUE TITLE
Allow to define a timeout for each experiment

### ISSUE THREAD

**Issue by RobertBuhren** [Fraunhofer-AISEC/archie#47]
Currently ARCHIE determines the end of an experiment by looking at the number of instructions that are encountered ("max_instruction_count") or by reaching a defined address ("end").

However, there are conditions where neither "max_instruction_count" is reached nor the address defined in "end" is reached:

- A bug in the QEMU machine model was triggered by the fault injection. If the bug enters end endless loop in the host process, ARCHIE will never finish the experiments.
- I encountered a case where an injected fault caused a write of the value "0xFFFFFFFD΅" to the SCTRL reg (ARMv7). QEMU continued to run, but the guest code was not executing anymore (probably due to the fact that paging was enabled but no valid pagetable  was present). As QEMU did not execute any instructions "max_instruction_count" was never reached and the experiment was never finished.

Regards,

Robert

**Comment by e-shreve-ti** [comment]
Another condition that triggers this issue is if a wait-for-interrupt instruction is executed but no interrupt is ever generated. This may be a common condition for Cortex M class emulations.

**Comment by aewag** [comment]
Resolved in #80. Timeout is now part of the configuration.
